version: '3.8'

services:

  postgresql:
    image: postgres
    ports:
      - 5434:5432
    environment: 
      POSTGRES_USER: alura
      POSTGRES_PASSWORD: alura
      POSTGRES_DB: alura_db
    volumes:
      - database-data-alura-db:/var/lib/postgresql/data/

volumes:
  database-data-alura-db:

